# Generated by Django 3.2.8 on 2021-10-31 03:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 3, 44, 6, 779382, tzinfo=utc))),
                ('isNew', models.BooleanField(default=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_noti', to='user_message.message')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_message', to=settings.AUTH_USER_MODEL)),
                ('user_notified', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notified_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
