# Generated by Django 3.2.8 on 2021-10-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'useraccount', 'verbose_name_plural': 'useraccounts'},
        ),
    ]
