# Generated by Django 3.2.8 on 2021-10-31 03:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 3, 44, 6, 774210, tzinfo=utc)),
        ),
    ]
