# Generated by Django 3.2.8 on 2021-10-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='isNew',
            field=models.BooleanField(choices=[(1, 'True'), (2, 'False')], default=1),
        ),
    ]
