# Generated by Django 3.2.8 on 2021-10-26 18:26

from django.db import migrations
import user_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_auto_20211026_1641'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_account.models.UserManager()),
            ],
        ),
    ]
