# Generated by Django 3.2.8 on 2021-10-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='picture',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='images/'),
        ),
    ]
