# Generated by Django 3.2.8 on 2021-11-01 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_notification', '0002_alter_reviewnotification_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewnotification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 18, 10, 161238, tzinfo=utc)),
        ),
    ]
